### ISSUE TITLE
./gradlew :plugin:assemble error

### ISSUE THREAD

**Issue by indegro** [typelead/intellij-eta#17]
I have cloned  intellij-eta repository.
Tried to build it and got the error. 

> ddushyn@EMPTY_BOX:/mnt/c/work/projects/eta/intellij-eta$ ./gradlew :plugin:assemble
> 
> /mnt/c/work/projects/eta/intellij-eta/eta-parser/gen/src/Language/Eta/Utils/FiniteMap.hs:27:20: warning:
    In the use of ‘Map.fold’ (imported from Data.Map):
    Deprecated: "As of version 0.5, replaced by 'foldr'."
   |
27 | foldRight        = Map.fold
   |                    ^^^^^^^^
>
>/mnt/c/work/projects/eta/intellij-eta/eta-parser/gen/src/Language/Eta/Core/TrieMap.hs:110:18: warning:
    In the use of ‘IntMap.fold’ (imported from Data.IntMap):
    Deprecated: "As of version 0.5, replaced by 'foldr'."
    |
110 |   foldTM k m z = IntMap.fold k z m
    |                  ^^^^^^^^^^^

> /mnt/c/work/projects/eta/intellij-eta/eta-parser/gen/src/Language/Eta/Core/TrieMap.hs:121:18: warning:
    In the use of ‘Map.fold’ (imported from Data.Map):
    Deprecated: "As of version 0.5, replaced by 'foldr'."
    |
121 |   foldTM k m z = Map.fold k z m
    |                  ^^^^^^^^
>
> /mnt/c/work/projects/eta/intellij-eta/eta-parser/gen/src/Language/Eta/Core/TrieMap.hs:759:23: warning:
    In the use of ‘Map.fold’ (imported from Data.Map):
    Deprecated: "As of version 0.5, replaced by 'foldr'."
    |
759 | foldTyLit l m = flip (Map.fold l) (tlm_string m)
    |                       ^^^^^^^^

> /mnt/c/work/projects/eta/intellij-eta/eta-parser/gen/src/Language/Eta/Core/TrieMap.hs:760:23: warning:
    In the use of ‘Map.fold’ (imported from Data.Map):
    Deprecated: "As of version 0.5, replaced by 'foldr'."
    |
760 |               . flip (Map.fold l) (tlm_number m)
    |                       ^^^^^^^^
> etlas: Could not resolve dependencies:
> trying: plugin-0.0.0 (user goal)
> trying: eta-parser-0.0.1.0/installed-inp... (dependency of plugin-0.0.0)
> next goal: text (dependency of eta-parser-0.0.1.0/installed-inp...)
> rejecting: text-1.2.2.2/installed-ab7... (conflict: text =>
> eta-java-interop==0.1.5.0/installed-142..., plugin => eta-java-interop>=0.1.3
&& <0.1.4)
> rejecting: text-1.2.2.2/installed-c40..., text-1.2.3.0, text-1.2.2.2,
> text-1.2.2.1, text-1.2.2.0, text-1.2.1.3, text-1.2.1.2, text-1.2.1.1,
> text-1.2.1.0, text-1.2.0.6, text-1.2.0.5, text-1.2.0.4, text-1.2.0.3,
> text-1.2.0.2, text-1.2.0.0, text-1.1.1.4, text-1.1.1.3, text-1.1.1.2,
> text-1.1.1.1, text-1.1.1.0, text-1.1.0.1, text-1.1.0.0, text-1.0.0.1,
> text-1.0.0.0, text-0.11.3.1, text-0.11.3.0, text-0.11.2.3, text-0.11.2.2,
> text-0.11.2.1, text-0.11.2.0, text-0.11.1.13, text-0.11.1.12, text-0.11.1.11,
> text-0.11.1.10, text-0.11.1.9, text-0.11.1.8, text-0.11.1.7, text-0.11.1.6,
text-0.11.1.5, text-0.11.1.3, text-0.11.1.2, text-0.11.1.1, text-0.11.1.0,
text-0.11.0.8, text-0.11.0.7, text-0.11.0.6, text-0.11.0.5, text-0.11.0.4,
text-0.11.0.3, text-0.11.0.2, text-0.11.0.1, text-0.11.0.0, text-0.10.0.2,
text-0.10.0.1, text-0.10.0.0, text-0.9.1.0, text-0.9.0.1, text-0.9.0.0,
text-0.8.1.0, text-0.8.0.0, text-0.7.2.1, text-0.7.1.0, text-0.7.0.1,
text-0.7, text-0.6, text-0.5, text-0.4, text-0.3, text-0.2, text-0.1
(conflict: eta-parser => text==1.2.2.2/installed-ab7...)
fail (backjumping, conflict set: eta-parser, plugin, text)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: eta-parser, text, plugin
> Task :plugin:installDependenciesEta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugin:installDependenciesEta'.
> Nonzero (1) exit code for command [/home/ddushyn/.gradle/caches/etlas/1.3.0.0/etlas, --select-eta=0.7.2b1, deps] with workingDir /mnt/c/work/projects/eta/intellij-eta/plugin/build/eta/main
  Process Standard Output:
  Resolving dependencies...
  Process Standard Error:
  etlas: Could not resolve dependencies:
  trying: plugin-0.0.0 (user goal)
  trying: eta-parser-0.0.1.0/installed-inp... (dependency of plugin-0.0.0)
  next goal: text (dependency of eta-parser-0.0.1.0/installed-inp...)
  rejecting: text-1.2.2.2/installed-ab7... (conflict: text =>
  eta-java-interop==0.1.5.0/installed-142..., plugin => eta-java-interop>=0.1.3
  && <0.1.4)
  rejecting: text-1.2.2.2/installed-c40..., text-1.2.3.0, text-1.2.2.2,
  text-1.2.2.1, text-1.2.2.0, text-1.2.1.3, text-1.2.1.2, text-1.2.1.1,
  text-1.2.1.0, text-1.2.0.6, text-1.2.0.5, text-1.2.0.4, text-1.2.0.3,
  text-1.2.0.2, text-1.2.0.0, text-1.1.1.4, text-1.1.1.3, text-1.1.1.2,
  text-1.1.1.1, text-1.1.1.0, text-1.1.0.1, text-1.1.0.0, text-1.0.0.1,
  text-1.0.0.0, text-0.11.3.1, text-0.11.3.0, text-0.11.2.3, text-0.11.2.2,
  text-0.11.2.1, text-0.11.2.0, text-0.11.1.13, text-0.11.1.12, text-0.11.1.11,
  text-0.11.1.10, text-0.11.1.9, text-0.11.1.8, text-0.11.1.7, text-0.11.1.6,
  text-0.11.1.5, text-0.11.1.3, text-0.11.1.2, text-0.11.1.1, text-0.11.1.0,
  text-0.11.0.8, text-0.11.0.7, text-0.11.0.6, text-0.11.0.5, text-0.11.0.4,
  text-0.11.0.3, text-0.11.0.2, text-0.11.0.1, text-0.11.0.0, text-0.10.0.2,
  text-0.10.0.1, text-0.10.0.0, text-0.9.1.0, text-0.9.0.1, text-0.9.0.0,
  text-0.8.1.0, text-0.8.0.0, text-0.7.2.1, text-0.7.1.0, text-0.7.0.1,
  text-0.7, text-0.6, text-0.5, text-0.4, text-0.3, text-0.2, text-0.1
  (conflict: eta-parser => text==1.2.2.2/installed-ab7...)
  fail (backjumping, conflict set: eta-parser, plugin, text)
  After searching the rest of the dependency tree exhaustively, these were the
  goals I've had most trouble fulfilling: eta-parser, text, plugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17m 48s
19 actionable tasks: 16 executed, 3 up-to-date
ddushyn@EMPTY_BOX:/mnt/c/work/projects/eta/intellij-eta$

`

**Comment by indegro** [comment]
Env:
Java
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

stack 
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2

**Comment by rahulmutt** [comment]
@indegro Can you try running `/home/ddushyn/.gradle/caches/etlas/1.3.0.0/etlas update` and run the build again after doing `./gradlew clean`.

**Comment by indegro** [comment]
Thank you! It helped :)

**Comment by rahulmutt** [comment]
Since this looks resolved, I'm closing this.
