### ISSUE TITLE
Improper submodule ref for eta-parser

### ISSUE THREAD

**Issue by Sir4ur0n** [typelead/intellij-eta#21]
Hi,

Is this maintained? It doesn't even compile on my computer.
```bash
$ git submodule update --init --recursive
# error: Server does not allow request for unadvertised object d41ce1a55f84314dc07edd0aad315319450ac00c
# Fetched in submodule path 'eta-parser', but it did not contain d41ce1a55f84314dc07edd0aad315319450ac00c. Direct fetching of that commit failed.
```

**Comment by carymrobbins** [comment]
@Sir4ur0n Try out the `use-eta-parser-intellij-gen` branch, that should resolve the issue. See PR #22.

**Comment by Sir4ur0n** [comment]
I managed to build it and run it using `./gradlew :plugin:runIde` but simply importing the `eta-init` project from the tutorial brought my CPU to 700% 😄

**Comment by carymrobbins** [comment]
@Sir4ur0n Would you mind opening that as a separate issue including the steps you took to import the project? You might also want to check the [IntelliJ logs](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) and report any stack traces you see relating to `typelead`.

**Comment by Sir4ur0n** [comment]
Shouldn't this issue be closed only when the PR is merged?

**Comment by rahulmutt** [comment]
@Sir4ur0n Can you file a new detailed issue on how to reproduce the CPU usage issue?
